services:
  authentication-service:
    build:
      context: ../../
      dockerfile: apps/authentication-service/Dockerfile
      target: runner
    environment:
      - DATABASE_URL=postgresql://${AUTHENTICATION_DB_USER}:${AUTHENTICATION_DB_PASSWORD}@db_authentication:5432/${AUTHENTICATION_DB}
    ports:
      - "8083:8083"
    depends_on:
      - db_authentication

  db_authentication:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${AUTHENTICATION_DB}
      POSTGRES_USER: ${AUTHENTICATION_DB_USER}
      POSTGRES_PASSWORD: ${AUTHENTICATION_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_authentication_data:/var/lib/postgresql/data

volumes:
  db_authentication_data:
