services:
  api-gateway:
    build:
      context: .
      target: runner
    environment:
      - ANALYTICS_SERVICE_URL=${ANALYTICS_SERVICE_URL}
      - AUTHENTICATION_SERVICE_URL=${AUTHENTICATION_SERVICE_URL}
      - URL_SHORTENING_SERVICE_URL=${URL_SHORTENING_SERVICE_URL}
    ports:
      - "8080:8080"
